samples:
    fastq: [data/split_read.1.fq.gz, data/split_read.2.fq.gz]
    fq_path: "../fastq"
    lanes: [V300031291_L01]
    id: "data"
    chroms: [chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY]
modules:
    variant_calling: False
    benchmarking: False
    phasing: False
    mate_pair_analysis: False
    read_overlap_analysis: False
    duplicate_plot: False
    umi_analysis: False
params:
    ref_fa: "/research/rv-02/home/eanderson/cgi-wgs-pipeline/data_and_tools/data/hs37d5/hs37d5_chrfix.fa"
    platform: "BGI-seq"
    read_len: 100 
    toolsdir: "/research/rv-02/home/eanderson/CGI_WGS_Pipeline/Data_and_Tools"
    barcode: "/barcode.list"
    barcode_RC: "/barcode_RC.list"
    sentieon_install: "/opt/sentieon-genomics-201808.07"
    sentieon_license: "SENTIEON_LICENSE=sentieon-license-server.completegenomics.com:8990"
    wenlan_python: "/opt/cgi-anaconda2-4.4.0/bin/python"
    gcbias_python: "/research/rv-02/home/qmao/Scripts/python_virtualenv/python_packages/env/bin/python"
    dbsnp_path: "/research/rv-02/home/eanderson/Resources_And_DBs/dbsnp_138.hg38.chrfix.vcf.gz"
    sentieon_model: "/research/rv-02/home/eanderson/CGI_WGS_Pipeline/Data_and_Tools/data/DNAscope_BGI_model_beta.txt"
    gc_bias_index: "/research/rv-02/home/eanderson/CGI_WGS_Pipeline/Data_and_Tools/data/hg38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa.500.gc"
calc_frag:
    split_dist: [300000, 50000]
    min_frag: 750
    include_dups: True
benchmark:
    benchmark_snp: "/research/rv-02/home/qmao/DBs/hg38_benchmark_ref/NA12878.GIAB.hg38.snp.vcf.gz"
    benchmark_indel: "/research/rv-02/home/qmao/DBs/hg38_benchmark_ref/NA12878.GIAB.hg38.indel.vcf.gz"
    bedfile: "/research/rv-02/home/qmao/DBs/hg38_benchmark_ref/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7.bed"
    ref_sdf: "/research/rv-02/home/qmao/DBs/hg38_benchmark_ref/GRCh38.sdf"
threads:
    bwa: 100
    haplotyper: 100
    metrics: 10
    gnu_parallel: 20
    calc_frag: 8
